# permissions for end users to edit brokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: broker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eclipse-mosquitto-mqtt-broker-operator
    app.kubernetes.io/part-of: eclipse-mosquitto-mqtt-broker-operator
    app.kubernetes.io/managed-by: kustomize
  name: broker-editor-role
rules:
- apiGroups:
  - mosquitto.oliversmith.io.oliversmith.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mosquitto.oliversmith.io.oliversmith.io
  resources:
  - brokers/status
  verbs:
  - get
